mystr = "sayaka is the best girl from danganronpa"
mystr1 = "77"
print(int(mystr1)+ 10)
print(mystr1 + mystr)
print(mystr[4])
print(mystr[0:4])
print(len(mystr))
print(mystr[0:40])
print(mystr[0:49])
print(mystr[0:40:2])
print(mystr[0:])
print(mystr[ :4])
print(mystr[::20])
print(mystr[-3:-1:1])
print(mystr[-3::-1])
print(type(mystr))
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith ( "pa"))
print(mystr.count("a"))
print(mystr.capitalize())
print(mystr.find("girl"))
print(mystr.upper())
print(mystr.replace("the" , ""))
